In [47]:
import numpy as np
import hashlib

Name A: 

Name B: 

In [48]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [49]:

k_shingles =    [["big", "data", "platform", "students", "blackboard"],
                 ["questions", "minhash", "project", "ntnu", "students", "piazza"],
                 ["ntnu", "big", "data", "platform", "blackboard", "piazza"],
                 ["project", "data", "students", "blackboard", "piazza"],
                ]


unique_words = sorted(['big', 'data', 'platform', 'students', 'blackboard', 'questions', 'minhash', 'project', 'ntnu', 'piazza']) # Enter the unique words list here

In [50]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Incorrect! Try again.


In [51]:


Input_Matrix = np.empty([10, 4]) # Create an empty array of input matrix

In [52]:
## Compute the values for the input matrix here ##

def hash(x,length,s1,s2): 
    return (s1*x+s2)%(length+1)

for i, word in enumerate(unique_words):
    for j, k_shingle in enumerate(k_shingles):
        if word in k_shingle:
            Input_Matrix[i][j] = 1
        else:
            Input_Matrix[i][j] = 0

for i in range(len(Input_Matrix)):
    print(Input_Matrix[i])

[1. 0. 1. 0.]
[1. 0. 1. 1.]
[1. 0. 1. 1.]
[0. 1. 0. 0.]
[0. 1. 1. 0.]
[0. 1. 1. 1.]
[1. 0. 1. 0.]
[0. 1. 0. 1.]
[0. 1. 0. 0.]
[1. 1. 0. 1.]


In [53]:
Sig_M = np.full((3, 4), np.inf) # Create a MinHash signature matrix array with inf values

In [54]:
# Generate hash functions
hash_seeds=[[1,3],[7,1],[7,2]]

def minhash(matrix, num_hashes):
    num_rows, num_cols = matrix.shape
    minhash_matrix = np.full((num_hashes, num_cols), np.inf)

    for r in range(num_rows):
        for c in range(num_cols):
            if matrix[r][c] == 1:
                for i in range(num_hashes):
                    hash_val = hash(r, num_rows, hash_seeds[i][0], hash_seeds[i][1])
                    if hash_val < minhash_matrix[i][c]:
                        minhash_matrix[i][c] = hash_val

    return minhash_matrix

def hash(x,length,s1,s2):
    return (s1*x+s2)%(length+1)

# Example usage:

num_hashes = len(hash_seeds)
minhash_matrix = minhash(np.array(Input_Matrix), num_hashes)

0 0 10 1 3 3
0 0 10 7 1 1
0 0 10 7 2 2
0 2 10 1 3 3
0 2 10 7 1 1
0 2 10 7 2 2
1 0 10 1 3 4
1 0 10 7 1 8
1 0 10 7 2 9
1 2 10 1 3 4
1 2 10 7 1 8
1 2 10 7 2 9
1 3 10 1 3 4
1 3 10 7 1 8
1 3 10 7 2 9
2 0 10 1 3 5
2 0 10 7 1 4
2 0 10 7 2 5
2 2 10 1 3 5
2 2 10 7 1 4
2 2 10 7 2 5
2 3 10 1 3 5
2 3 10 7 1 4
2 3 10 7 2 5
3 1 10 1 3 6
3 1 10 7 1 0
3 1 10 7 2 1
4 1 10 1 3 7
4 1 10 7 1 7
4 1 10 7 2 8
4 2 10 1 3 7
4 2 10 7 1 7
4 2 10 7 2 8
5 1 10 1 3 8
5 1 10 7 1 3
5 1 10 7 2 4
5 2 10 1 3 8
5 2 10 7 1 3
5 2 10 7 2 4
5 3 10 1 3 8
5 3 10 7 1 3
5 3 10 7 2 4
6 0 10 1 3 9
6 0 10 7 1 10
6 0 10 7 2 0
6 2 10 1 3 9
6 2 10 7 1 10
6 2 10 7 2 0
7 1 10 1 3 10
7 1 10 7 1 6
7 1 10 7 2 7
7 3 10 1 3 10
7 3 10 7 1 6
7 3 10 7 2 7
8 1 10 1 3 0
8 1 10 7 1 2
8 1 10 7 2 3
9 0 10 1 3 1
9 0 10 7 1 9
9 0 10 7 2 10
9 1 10 1 3 1
9 1 10 7 1 9
9 1 10 7 2 10
9 3 10 1 3 1
9 3 10 7 1 9
9 3 10 7 2 10


In [55]:
hash_1 = list(minhash_matrix[0])

In [56]:
hash_2 = list(minhash_matrix[1])

In [57]:
hash_3 = list(minhash_matrix[2])

In [58]:
hash_list = [hash_1, hash_2, hash_3]

In [59]:
hash_list

[[1.0, 0.0, 3.0, 1.0], [1.0, 0.0, 1.0, 3.0], [0.0, 1.0, 0.0, 4.0]]

In [60]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##
Sig_M=minhash_matrix

In [61]:
# print the updated MinHash signature matrix

Sig_M

array([[1., 0., 3., 1.],
       [1., 0., 1., 3.],
       [0., 1., 0., 4.]])